# Generated by Django 5.1.6 on 2025-09-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu', models.FloatField()),
                ('kelembapan', models.FloatField()),
                ('hasil_ai', models.CharField(max_length=50)),
                ('rekomendasi', models.CharField(blank=True, max_length=100)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu', models.FloatField()),
                ('kelembapan', models.FloatField()),
                ('status_kipas', models.CharField(blank=True, max_length=20)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
