# Generated by Django 5.1.6 on 2025-11-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('fan_status', models.CharField(default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FanControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_status', models.CharField(default='OFF', max_length=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('manual_override', models.BooleanField(default=False)),
            ],
        ),
    ]
